name: .NET Core Build
 
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
        
    - uses: lauchacarro/netcore-action-template@master
      with:
        who-to-greet: 'world'
